### ISSUE TITLE
Update the documentation of "prepareReadRecordFile" methods

### ISSUE THREAD

**Issue by andrei-cristea** [calypsonet/calypsonet-terminal-calypso-java-api#13]
`CalypsoCardSelection.prepareReadRecordFile(byte sfi, int recordNumber)`:
- Indicate that the method does not generate an error if the `recordNumber` does not exist.

`CardTransactionManager.prepareReadRecordFile(byte sfi, int recordNumber)`: 
- Indicate that the method does not generate an error if the `recordNumber` does not exist.
- Indicate that this method must not be used **in a secure session while in contact mode** (use the other method for this case by providing correct parameters).

`CardTransactionManager.prepareReadRecordFile(byte sfi, int firstRecordNumber, int numberOfRecords, int recordSize)`:
- Indicate that the method does not generate an error if the `numberOfRecords` or the `recordSize` are incorrect.
- Indicate that this method must be used with correct parameters in a secure session, otherwise the session will fail when closed.

To keep the API design homogeneous, it is also necessary to modify the signature of all methods that can throw a `NoSuchElementException` so that they return a null value, empty list, empty map, etc... This will not have a major impact on the version because the behavior of the read methods is more tolerant than before.

**Comment by jeanpierrefortune** [comment]
The best effort behavior requested must be extended to SFI management, i.e. not generate an error if the file whose SFI is provided does not exist.
