### ISSUE TITLE
Managing sam unlock at selection when unlockData needs to be diversified.

### ISSUE THREAD

**Issue by lbureau-billettiqueservices** [calypsonet/calypsonet-terminal-calypso-java-api#51]
Hey everyone. I'm thinking that i'm missing a detail or something about the use of `CalypsoSamSelection`.

Let's see this simple piece of code.

```java
CalypsoSamSelection samSelection = calypsoExtensionService.createSamSelection();
samSelection.setUnlockData(unlockData);

CardSelectionManager selectionManager = smartCardService.createCardSelectionManager();
selectionManager.prepareSelection(samSelection);

CardSelectionResult selectionResult = selectionManager.processCardSelectionScenario(samReader);
calypsoSam = (CalypsoSam) selectionResult.getActiveSmartCard();
```

I have a problem with how unlockData is handled. What I can see in `CalypsoSamSelectionAdapter`, the unlockData passed to `setUnlockData` is used "as is", with no diversification.

Unlock key diversification is done using the SAM's serial number, which would mean that i would need to make a previous selection without unlock data to get the `CalypsoSam` object, get the SAM Serial, diversify it myself, then redo another selection with unlock.

It might be clearly possible that i'm missing a `unlockSam` method somewhere that i could call after selection, but I could not see one (and i could only find the object `CmdSamUnlock` in `CalypsoSamSelectionAdapter`).

If i'm not missing anything, i would propose this slight change in interface:

* make a new method `setRawUnlockData` that behaves like the current `setUnlockData`
* mark `setUnlockData` as deprecated
* make a new method `setUnlockDataWithDiversifier(String unlockData, Diversifier diversification)`

Diversifier would like this:

```java
public interface Diversifier {
    byte[] diversify(CalypsoSam sam, byte[] masterKey)
}
```

That way, we can provide our own diversifier (the usual key diversification is, as far as i know, supposed to be secret, so implementing it directly into keyple (which is public) would break this).

The idea behind this would be that keyple should attempt the unlock using the diversified key from the diversifier object when doing the selection.

**Comment by lbureau-billettiqueservices** [comment]
That is indeed what we do currently. It feels a little bit awkward, but it works.

As long as this use case is in the pipeline somehow (considering it is very common!), i'm fine with it. Thanks!

**Comment by jeanpierrefortune** [comment]
Hello Laurent,

We've just released a new version of the Keypop API and the corresponding Keyple library to enable advanced unlocking modes of the SAM.

It is now possible to compute a diversified version of the unlock value within the application, or to have it computed by an origin SAM in dynamic mode.

These modes are only available for components implementing the Keypop interfaces.

- [keypop-calypso-crypto-legacysam-api 0.4.0](https://www.keypop.org/apis/keypop-calypso-crypto-legacysam-api/)
- [keyple-card-calypso-crypto-legacysam-lib 0.5.0](https://keyple.org/components/card-extensions/keyple-card-calypso-crypto-legacysam-lib/)

Regards
